### ISSUE TITLE
USER STORY: MENU #3

### ISSUE THREAD

**Issue by Mvogtsinga** [Mvogtsinga/week-food-foot#3]
As a **Customer** I can see the Menu, so that I can have information about products served in restaurant.

# Acceptance criteria

- A "Menu" card must be present on subpage
- Being clicked on Menu's tab, the User had access to Menu

# Tasks

- [ ] Add and style "Menu" tab
- [ ] Add onclick javascript function to the button to activate the modal with picture of the menu
- [ ] add close button to the modal if necessary
