### ISSUE TITLE
USER STORY: LOGIN # 4

### ISSUE THREAD

**Issue by Mvogtsinga** [Mvogtsinga/week-food-foot#4]
As a User,I can normally access "Login" window, so I can be redirecting to the **homepage**

# Acceptance criteria

- The "Login" must be easy to find 
- After "Login", the user must be redirect to the homepage
- The customer user must have access to important information, like: restaurant, menu, contact,book a table

# Tasks

- [x] Design a homepage with login window

- [x] Assign a link to a button
- [x] Design "Login" page
