### ISSUE TITLE
USER STORY: RESERVATION CANCELLATION #5

### ISSUE THREAD

**Issue by Mvogtsinga** [Mvogtsinga/week-food-foot#5]
As a Customer, I can cancel my reservation, so that the restaurant is aware about my absence in advance.

# Acceptance criteria

- User must have an existing account to be able to log in to the reservation system
- User cannot access the reservation system without logging in
- User must confirm cancellation
- Superuser must get a notification on User's cancellation

# Tasks

- [ ] Add "cancellation" CRUD logic to the User's reservation model
- [ ] Add the "Cancel Reservation" button to frontend for the User
- [ ] Add a Cancellation confirmation message
