### ISSUE TITLE
USER STORY: BOOK A TABLE #6

### ISSUE THREAD

**Issue by Mvogtsinga** [Mvogtsinga/week-food-foot#6]
As a Customer, I can book a table, so that I can visit the restaurant with the assurance to have a attribute table.

#Acceptance criteria
- User must have an existing account to be able to log in to the reservation system
- User cannot access to "My reservations" without logging in
- Superuser must be able to see the reservation information to approve or decline it (backend)
- User must be able to see if his reservation has been confirmed

# Tasks

- [x] creating table reservation model as a backend 

- [x] Creating a frontend "Reservation form"
- [x] Adding a status confirmation to  "My reservations" for User to see
- [x] Add edit reservation model
