### ISSUE TITLE
USER STORY: DEPLOYMENT

### ISSUE THREAD

**Issue by Mvogtsinga** [Mvogtsinga/week-food-foot#8]
As a **Developer** I can deploy the website early and by important change, so that I can avoid additional stress and technical issues in the moment of the project submission.

# Acceptance criteria:

The project must be deployed to Heroku

- The project must be connected to the 3rd party database like ElephantSQL
- The code must be stored on GitHub to be evaluateted by the assessor
- The project must be displayed through GitHub app

# Tasks:

- [x] Creating a workspace with Gitpod
- [x] Connecting Github to Heroku
- [x] Installing dependencies
- [x] Setting up the enviroment variables
- [ ] connecting ElephantSQL
- [ ] Ensuring that app is displaying properly on Heroku
- [ ] Connect to Cloudinary to Django and Heroku
